// apps/pomo-angular/src/app/chip/chip.component.ts
import { Component, Input } from '@angular/core';
// import BrainSvg from '@pomo/assets/icons/ph_brain-fill.svg';
// import CoffeeSvg from '@pomo/assets/icons/ph_coffee.svg';

type TimerState = 'focus' | 'break-short' | 'break-long';
@Component({
  selector: 'app-chip',
  templateUrl: './chip.component.html',
})
export class ChipComponent {
  @Input({ required: true }) variant: TimerState = 'focus';
  config = {
    focus: {
      icon: '@pomo/assets/icons/ph_brain-fill.svg',
      text: 'Focus',
    },
    'break-long': {
      icon: '@pomo/assets/icons/ph_coffee.svg',
      text: 'Break long',
    },
    'break-short': {
      icon: '@pomo/assets/icons/ph_coffee.svg',
      text: 'Break short',
    },
  };
}

<div
  class="flex items-center gap-x-9px border-2 border-solid border-primary-900 dark:border-primary-50 bg-primary-a-100 text-primary-900 dark:text-primary-50 rounded-999px px-4 py-2 font-medium"
>
  <!-- <img src="../../assets/ph_brain-fill.svg" alt="" /> -->
  <img src="/@pomo/assets/icons/ph_brain-fill.svg" alt="" />
  <!-- 
  <svg-icon
    src="{{ config[variant].icon }}"
    class="stroke-primary-900 dark:stroke-primary-50"
  ></svg-icon> -->

  {{ config[variant].text }}
</div>

// apps/pomo-react/src/components/chip.tsx
import { FC } from 'react'
import { ReactComponent as BrainSvg } from '@pomo/assets/icons/ph_brain-fill.svg'
import { ReactComponent as CoffeeSvg } from '@pomo/assets/icons/ph_coffee.svg'

const config = {
	focus: {
		icon: <BrainSvg className='stroke-primary-900 dark:stroke-primary-50' />,
		text: 'Focus',
	},
	'break-long': {
		icon: <CoffeeSvg className='stroke-primary-900 dark:stroke-primary-50' />,
		text: 'Break long',
	},
	'break-short': {
		icon: <CoffeeSvg className='stroke-primary-900 dark:stroke-primary-50' />,
		text: 'Break short',
	},
}

export const Chip: FC<{
	variant: 'focus' | 'break-long' | 'break-short'
}> = ({ variant }) => {
	return (
		<div className='flex items-center gap-x-[9px] border-2 border-solid border-primary-900 dark:border-primary-50 bg-primary-a-100 text-primary-900 dark:text-primary-50 rounded-[999px] px-4 py-2 font-medium'>
			{config[variant].icon}
			{config[variant].text}
		</div>
	)
}
