// apps/pomo-vue/src/App.vue
<script setup lang="ts">
import { inject, ref, computed } from 'vue'
import { useToast } from 'vue-toastification'
import DotsSvg from '@pomo/assets/icons/ph_dots-three-outline-fill.svg'
import PlaySvg from '@pomo/assets/icons/ph_play-fill.svg'
import PauseSvg from '@pomo/assets/icons/ph_pause-fill.svg'
import ForwardSvg from '@pomo/assets/icons/ph_fast-forward-fill.svg'

import Timer from './components/Timer.vue'
import Chip from './components/Chip.vue'
import AppButton from './components/AppButton.vue'
import { TIMER_STATES, NOTIFICATION_MESSAGES } from './app-constants'
import SettingsModal from './components/SettingsModal.vue'
import { Settings, TimerState } from './types'

const toast = useToast()

const settings = inject<Settings>('settings')!
const state = ref(0)
const isPlaying = ref(false)

const changeState = () => {
	isPlaying.value = false
	const nextState = (state.value + 1) % TIMER_STATES.length
	state.value = nextState

	if (settings.hasNotifications) {
		toast.success(`Current state - ${NOTIFICATION_MESSAGES[TIMER_STATES[state.value]]}`)
	}
	// appdb.put('state', nextState, 'state').catch(noop)
}

const toggleIsPlaying = () => {
	isPlaying.value = !isPlaying.value
}
const onTimerComplete = () => {
	isPlaying.value = false
}

const isOpen = ref(false)
const openModal = () => {
	isOpen.value = true
}
const closeModal = () => {
	isOpen.value = false
}

const initialTimes = computed<Record<TimerState, number>>(() => ({
	focus: settings.focusLength,
	'break-long': settings.longBreakLength,
	'break-short': settings.shortBreakLength,
}))
const initialTimeInSeconds = computed(() => initialTimes.value[TIMER_STATES[state.value]])
</script>

<template>
	<div
		className="h-full flex bg-primary-50 dark:bg-primary-950 text-primary-900 dark:text-primary-50 overflow-hidden"
	>
		<SettingsModal
			:isOpen="isOpen"
			@close="closeModal"
		/>
		<div className="max-w-[340px] px-[10px] m-auto flex-grow">
			<div className="flex items-center flex-col gap-y-3 md:gap-y-8">
				<Chip :variant="TIMER_STATES[state]" />
				<Timer
					:onComplete="onTimerComplete"
					:isPlaying="isPlaying"
					:initialTimeInSeconds="initialTimeInSeconds"
				/>
				<div className="flex items-center gap-x-2 xs:gap-x-4">
					<AppButton
						size="md"
						variant="secondary"
						@click="openModal"
					>
						<span className="sr-only">settings</span>
						<DotsSvg />
					</AppButton>
					<AppButton
						size="lg"
						variant="primary"
						@click="toggleIsPlaying"
					>
						<span class="sr-only">{{ isPlaying ? 'pause' : 'play' }}</span>
						<component :is="isPlaying ? PauseSvg : PlaySvg" />
					</AppButton>
					<AppButton
						size="md"
						variant="secondary"
						@click="changeState"
					>
						<span className="sr-only">next state</span>
						<ForwardSvg />
					</AppButton>
				</div>
			</div>
		</div>
	</div>
</template>

// apps/pomo-react/src/App.tsx
import { useState } from 'react'
import { toast } from 'react-hot-toast'
import { NOTIFICATION_MESSAGES, TIMER_STATES, noop } from '@pomo/constants'

import { ReactComponent as PauseSvg } from '@pomo/assets/icons/ph_pause-fill.svg'
import { ReactComponent as PlaySvg } from '@pomo/assets/icons/ph_play-fill.svg'
import { ReactComponent as DotsSvg } from '@pomo/assets/icons/ph_dots-three-outline-fill.svg'
import { ReactComponent as ForwardSvg } from '@pomo/assets/icons/ph_fast-forward-fill.svg'

import { Chip } from './components/chip'
import { Button } from './components/button'
import { Timer } from './components/timer'
import { SettingsModal } from './components/settings-modal'
import { initialTimerState, appdb } from './storage/settings'
import { TimerState } from './types'
import { useSettings } from './store/settings'

function App() {
	const { focusLength, shortBreakLength, longBreakLength, hasNotifications } = useSettings()
	const [state, setState] = useState(initialTimerState ?? 0)
	const [isPlaying, setIsPlaying] = useState(false)
	const [isModalOpen, setIsModalOpen] = useState(false)

	const toggleTimer = () => {
		setIsPlaying(!isPlaying)
	}

	const openModal = () => setIsModalOpen(true)
	const closeModal = () => setIsModalOpen(false)

	const nextStep = () => {
		setIsPlaying(false)
		const nextState = (state + 1) % TIMER_STATES.length
		setState(nextState)
		appdb.put('state', nextState, 'state').catch(noop)
	}

	const changeState = () => {
		nextStep()

		if (hasNotifications) {
			toast.success(`Current state - ${NOTIFICATION_MESSAGES[TIMER_STATES[state]]}`)
		}
	}

	const onTimerComplete = () => {
		nextStep()
		toast.success(`${NOTIFICATION_MESSAGES[TIMER_STATES[state]]} timer is complete!`)
	}

	const initialTimes: Record<TimerState, number> = {
		focus: focusLength,
		'break-long': longBreakLength,
		'break-short': shortBreakLength,
	}
	const initialTimeInSeconds = initialTimes[TIMER_STATES[state]]

	return (
		<div className='h-full flex bg-primary-50 dark:bg-primary-950 text-primary-900 dark:text-primary-50 overflow-hidden'>
			<SettingsModal
				closeModal={closeModal}
				isOpen={isModalOpen}
			/>
			<div className='max-w-[340px] px-[10px] m-auto flex-grow'>
				<div className='flex items-center flex-col gap-y-3 md:gap-y-8'>
					<Chip variant={TIMER_STATES[state]} />
					<Timer
						onComplete={onTimerComplete}
						isPlaying={isPlaying}
						initialTimeInSeconds={initialTimeInSeconds}
					/>
					<div className='flex items-center gap-x-2 xs:gap-x-4'>
						<Button
							size='md'
							variant='secondary'
							onClick={openModal}
						>
							<span className='sr-only'>settings</span>
							<DotsSvg />
						</Button>
						<Button
							size='lg'
							variant='primary'
							onClick={toggleTimer}
						>
							<span className='sr-only'>{isPlaying ? 'pause' : 'play'}</span>
							{isPlaying ? <PauseSvg /> : <PlaySvg />}
						</Button>
						<Button
							size='md'
							variant='secondary'
							onClick={changeState}
						>
							<span className='sr-only'>next state</span>
							<ForwardSvg />
						</Button>
					</div>
				</div>
			</div>
		</div>
	)
}

export default App
